import type { Appointment } from "@/features/appointments/types";

/**
 * Mock veri bu tarihe göre kurgulanmıştır; gerçek Supabase entegrasyonunda
 * bugünün tarihi doğrudan kullanılacaktır.
 */
export const DEMO_TODAY = new Date("2026-07-22T00:00:00.000");

export const mockAppointments: Appointment[] = [
  // agent-1 — Elif Yılmaz
  {
    id: "appt-001",
    leadId: "lead-001",
    leadName: "Ahmet Yıldız",
    agentId: "agent-1",
    propertyId: "prop-001",
    propertyTitle: "Deniz Manzaralı 3+1 Daire",
    type: "gösterim",
    status: "tamamlandi",
    scheduledAt: "2026-07-06T10:00:00.000",
    durationMinutes: 60,
    note: "Daireyi beğendi, teklif hazırlanacak.",
  },
  {
    id: "appt-002",
    leadId: "lead-004",
    leadName: "Derya Kılıç",
    agentId: "agent-1",
    propertyId: "prop-004",
    propertyTitle: "Aile İçin Geniş 4+1 Daire",
    type: "görüşme",
    status: "tamamlandi",
    scheduledAt: "2026-07-10T14:00:00.000",
    durationMinutes: 45,
    note: "Bütçe ve kredi seçenekleri konuşuldu.",
  },
  {
    id: "appt-003",
    leadId: "lead-009",
    leadName: "Kemal Doğan",
    agentId: "agent-1",
    propertyId: "prop-008",
    propertyTitle: "Boğaza Yakın Müstakil Ev",
    type: "gösterim",
    status: "iptal",
    scheduledAt: "2026-07-18T11:00:00.000",
    durationMinutes: 60,
    note: "Müşteri son anda iptal etti, tekrar planlanacak.",
  },
  {
    id: "appt-004",
    leadId: "lead-013",
    leadName: "Onur Aslan",
    agentId: "agent-1",
    propertyId: "prop-012",
    propertyTitle: "Yeni Yapı 3+1 Daire",
    type: "gösterim",
    status: "planlandi",
    scheduledAt: "2026-07-22T10:00:00.000",
    durationMinutes: 60,
    note: "İlk gösterim, WhatsApp üzerinden teyit alındı.",
  },
  {
    id: "appt-005",
    leadId: "lead-017",
    leadName: "Tolga Yaman",
    agentId: "agent-1",
    propertyId: "prop-016",
    propertyTitle: "Çankaya'da 4+1 Daire",
    type: "görüşme",
    status: "onaylandi",
    scheduledAt: "2026-07-22T10:30:00.000",
    durationMinutes: 60,
    note: "Karşı teklif detayları görüşülecek.",
  },
  {
    id: "appt-006",
    leadId: "lead-021",
    leadName: "Zehra Güneş",
    agentId: "agent-1",
    propertyId: "prop-001",
    propertyTitle: "Deniz Manzaralı 3+1 Daire",
    type: "gösterim",
    status: "planlandi",
    scheduledAt: "2026-07-29T09:00:00.000",
    durationMinutes: 45,
    note: "Otopark kriterini yerinde kontrol edecek.",
  },

  // agent-2 — Mert Kaya
  {
    id: "appt-007",
    leadId: "lead-002",
    leadName: "Selin Aydın",
    agentId: "agent-2",
    propertyId: "prop-002",
    propertyTitle: "Boğaz Manzaralı 2+1 Daire",
    type: "gösterim",
    status: "tamamlandi",
    scheduledAt: "2026-07-08T13:00:00.000",
    durationMinutes: 60,
    note: "Olumlu geçti, ikinci görüşme planlanacak.",
  },
  {
    id: "appt-008",
    leadId: "lead-006",
    leadName: "Gizem Aksoy",
    agentId: "agent-2",
    propertyId: "prop-006",
    propertyTitle: "Ekonomik 1+1 Daire",
    type: "görüşme",
    status: "gelmedi",
    scheduledAt: "2026-07-14T15:00:00.000",
    durationMinutes: 45,
    note: "Randevuya gelmedi, telefonla ulaşılamadı.",
  },
  {
    id: "appt-009",
    leadId: "lead-010",
    leadName: "Leyla Turan",
    agentId: "agent-2",
    propertyId: "prop-009",
    propertyTitle: "Metroya Yakın 2+1 Daire",
    type: "gösterim",
    status: "tamamlandi",
    scheduledAt: "2026-07-20T10:00:00.000",
    durationMinutes: 60,
    note: "İkinci gösterim istendi, hafta sonu planlanacak.",
  },
  {
    id: "appt-010",
    leadId: "lead-014",
    leadName: "Pınar Yalçın",
    agentId: "agent-2",
    propertyId: "prop-013",
    propertyTitle: "Merkezi Ofis Katı",
    type: "gösterim",
    status: "planlandi",
    scheduledAt: "2026-07-22T14:30:00.000",
    durationMinutes: 60,
    note: "Ofis katı için yatırımcı gösterimi.",
  },
  {
    id: "appt-011",
    leadId: "lead-018",
    leadName: "Ufuk Bozkurt",
    agentId: "agent-2",
    propertyId: "prop-017",
    propertyTitle: "Nilüfer'de 3+1 Daire",
    type: "görüşme",
    status: "onaylandi",
    scheduledAt: "2026-07-25T09:30:00.000",
    durationMinutes: 45,
    note: "Hafta sonu gösterim sonrası değerlendirme görüşmesi.",
  },
  {
    id: "appt-012",
    leadId: "lead-022",
    leadName: "Berk Demirtaş",
    agentId: "agent-2",
    propertyId: "prop-002",
    propertyTitle: "Boğaz Manzaralı 2+1 Daire",
    type: "imza",
    status: "planlandi",
    scheduledAt: "2026-08-03T11:00:00.000",
    durationMinutes: 45,
    note: "Satış sözleşmesi imzası için noter randevusu.",
  },

  // agent-3 — Zeynep Demir
  {
    id: "appt-013",
    leadId: "lead-003",
    leadName: "Caner Öztürk",
    agentId: "agent-3",
    propertyId: "prop-003",
    propertyTitle: "Deniz Sıfır Villa",
    type: "gösterim",
    status: "onaylandi",
    scheduledAt: "2026-07-22T11:00:00.000",
    durationMinutes: 60,
    note: "İkinci kez gösterim, eş de katılacak.",
  },
  {
    id: "appt-014",
    leadId: "lead-007",
    leadName: "Hakan Er",
    agentId: "agent-3",
    propertyId: "prop-007",
    propertyTitle: "Site İçi 3+1 Daire",
    type: "görüşme",
    status: "tamamlandi",
    scheduledAt: "2026-07-12T10:00:00.000",
    durationMinutes: 45,
    note: "Kredi hesaplama detayları paylaşıldı.",
  },
  {
    id: "appt-015",
    leadId: "lead-011",
    leadName: "Murat Sezer",
    agentId: "agent-3",
    propertyId: "prop-010",
    propertyTitle: "Orman Manzaralı Villa",
    type: "gösterim",
    status: "planlandi",
    scheduledAt: "2026-07-23T10:00:00.000",
    durationMinutes: 60,
    note: "Villa gösterimi, ulaşım bilgisi paylaşıldı.",
  },
  {
    id: "appt-016",
    leadId: "lead-015",
    leadName: "Rıza Kurt",
    agentId: "agent-3",
    propertyId: "prop-014",
    propertyTitle: "Ana Cadde Üzeri Dükkan",
    type: "gösterim",
    status: "iptal",
    scheduledAt: "2026-07-16T09:00:00.000",
    durationMinutes: 60,
    note: "Bütçe uyuşmadığı için görüşme iptal edildi.",
  },
  {
    id: "appt-017",
    leadId: "lead-019",
    leadName: "Vildan Er",
    agentId: "agent-3",
    propertyId: "prop-018",
    propertyTitle: "Sahil Şeridi Villa",
    type: "gösterim",
    status: "planlandi",
    scheduledAt: "2026-08-01T13:00:00.000",
    durationMinutes: 90,
    note: "Uzun gösterim, sahil ve iskele dahil tur yapılacak.",
  },
  {
    id: "appt-018",
    leadId: "lead-023",
    leadName: "Ceyda Aktaş",
    agentId: "agent-3",
    propertyId: "prop-003",
    propertyTitle: "Deniz Sıfır Villa",
    type: "görüşme",
    status: "onaylandi",
    scheduledAt: "2026-07-24T13:00:00.000",
    durationMinutes: 45,
    note: "İkinci gösterim sonrası değerlendirme.",
  },

  // agent-4 — Burak Şahin
  {
    id: "appt-019",
    leadId: "lead-005",
    leadName: "Emre Polat",
    agentId: "agent-4",
    propertyId: "prop-005",
    propertyTitle: "Şık 2+1 Daire",
    type: "imza",
    status: "onaylandi",
    scheduledAt: "2026-07-22T16:00:00.000",
    durationMinutes: 45,
    note: "Tapu devri için son evraklar hazır.",
  },
  {
    id: "appt-020",
    leadId: "lead-008",
    leadName: "İrem Şahin",
    agentId: "agent-4",
    propertyId: "prop-011",
    propertyTitle: "Tarihi Dokuda 1+1 Daire",
    type: "gösterim",
    status: "tamamlandi",
    scheduledAt: "2026-07-15T10:00:00.000",
    durationMinutes: 60,
    note: "Restorasyon detayları hakkında bilgi verildi.",
  },
  {
    id: "appt-021",
    leadId: "lead-012",
    leadName: "Nazlı Çelik",
    agentId: "agent-4",
    propertyId: "prop-015",
    propertyTitle: "Yatırımlık Arsa",
    type: "görüşme",
    status: "gelmedi",
    scheduledAt: "2026-07-19T11:00:00.000",
    durationMinutes: 45,
    note: "İkinci kez ulaşılamadı, takip edilecek.",
  },
  {
    id: "appt-022",
    leadId: "lead-016",
    leadName: "Sibel Arslan",
    agentId: "agent-4",
    propertyId: "prop-005",
    propertyTitle: "Şık 2+1 Daire",
    type: "gösterim",
    status: "planlandi",
    scheduledAt: "2026-07-26T10:00:00.000",
    durationMinutes: 60,
    note: "Okula yakınlık kriteri nedeniyle tekrar gösterim.",
  },
  {
    id: "appt-023",
    leadId: "lead-020",
    leadName: "Yasin Koç",
    agentId: "agent-4",
    propertyId: "prop-011",
    propertyTitle: "Tarihi Dokuda 1+1 Daire",
    type: "gösterim",
    status: "planlandi",
    scheduledAt: "2026-08-05T14:00:00.000",
    durationMinutes: 60,
    note: "Site içi daire alternatifleri de sunulacak.",
  },
  {
    id: "appt-024",
    leadId: "lead-024",
    leadName: "Doğukan Ay",
    agentId: "agent-4",
    propertyId: "prop-015",
    propertyTitle: "Yatırımlık Arsa",
    type: "görüşme",
    status: "planlandi",
    scheduledAt: "2026-07-31T09:00:00.000",
    durationMinutes: 45,
    note: "Arkadaş tavsiyesiyle gelen ilk görüşme.",
  },
];
