import type { Property } from "@/features/properties/types";

export const mockProperties: Property[] = [
  {
    id: "prop-001",
    listingCode: "ARP-2026-001",
    title: "Deniz Manzaralı 3+1 Daire",
    description:
      "Caddebostan sahiline yürüme mesafesinde, güney cepheli, geniş balkonlu daire.",
    price: 8500000,
    city: "İstanbul",
    district: "Kadıköy",
    neighborhood: "Caddebostan",
    propertyType: "daire",
    rooms: "3+1",
    areaM2: 145,
    status: "aktif",
    agentId: "agent-1",
    updatedAt: "2026-07-20T09:00:00.000Z",
  },
  {
    id: "prop-002",
    listingCode: "ARP-2026-002",
    title: "Boğaz Manzaralı 2+1 Daire",
    description: "Etiler'de site içerisinde, asansörlü, kapalı otoparklı daire.",
    price: 4200000,
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Etiler",
    propertyType: "daire",
    rooms: "2+1",
    areaM2: 110,
    status: "aktif",
    agentId: "agent-2",
    updatedAt: "2026-07-18T10:30:00.000Z",
  },
  {
    id: "prop-003",
    listingCode: "ARP-2026-003",
    title: "Deniz Sıfır Villa",
    description: "Alaçatı'da özel havuzlu, deniz manzaralı müstakil villa.",
    price: 15000000,
    city: "İzmir",
    district: "Çeşme",
    neighborhood: "Alaçatı",
    propertyType: "villa",
    rooms: "5+2",
    areaM2: 320,
    status: "aktif",
    agentId: "agent-3",
    updatedAt: "2026-07-19T14:00:00.000Z",
  },
  {
    id: "prop-004",
    listingCode: "ARP-2026-004",
    title: "Aile İçin Geniş 4+1 Daire",
    description: "Barbaros Mahallesi'nde okula ve AVM'ye yakın geniş aile dairesi.",
    price: 6300000,
    city: "İstanbul",
    district: "Ataşehir",
    neighborhood: "Barbaros",
    propertyType: "daire",
    rooms: "4+1",
    areaM2: 180,
    status: "pasif",
    agentId: "agent-1",
    updatedAt: "2026-07-05T11:00:00.000Z",
  },
  {
    id: "prop-005",
    listingCode: "ARP-2026-005",
    title: "Şık 2+1 Daire",
    description: "Mecidiyeköy merkezinde, metroya 5 dakika mesafede daire.",
    price: 5100000,
    city: "İstanbul",
    district: "Şişli",
    neighborhood: "Mecidiyeköy",
    propertyType: "daire",
    rooms: "2+1",
    areaM2: 95,
    status: "satildi",
    agentId: "agent-4",
    updatedAt: "2026-07-15T09:30:00.000Z",
  },
  {
    id: "prop-006",
    listingCode: "ARP-2026-006",
    title: "Ekonomik 1+1 Daire",
    description: "Yeşilköy'de yatırıma uygun, kiracılı 1+1 daire.",
    price: 3000000,
    city: "İstanbul",
    district: "Bakırköy",
    neighborhood: "Yeşilköy",
    propertyType: "daire",
    rooms: "1+1",
    areaM2: 60,
    status: "aktif",
    agentId: "agent-2",
    updatedAt: "2026-07-10T08:00:00.000Z",
  },
  {
    id: "prop-007",
    listingCode: "ARP-2026-007",
    title: "Site İçi 3+1 Daire",
    description: "Kapalı site içerisinde, sosyal tesisli, güvenlikli daire.",
    price: 7200000,
    city: "İstanbul",
    district: "Ümraniye",
    neighborhood: "Çakmak",
    propertyType: "daire",
    rooms: "3+1",
    areaM2: 135,
    status: "aktif",
    agentId: "agent-3",
    updatedAt: "2026-07-21T13:00:00.000Z",
  },
  {
    id: "prop-008",
    listingCode: "ARP-2026-008",
    title: "Boğaza Yakın Müstakil Ev",
    description: "Kanlıca'da bahçeli, boğaza yürüme mesafesinde müstakil ev.",
    price: 9800000,
    city: "İstanbul",
    district: "Beykoz",
    neighborhood: "Kanlıca",
    propertyType: "mustakil-ev",
    rooms: "6+1",
    areaM2: 400,
    status: "aktif",
    agentId: "agent-1",
    updatedAt: "2026-07-17T10:00:00.000Z",
  },
  {
    id: "prop-009",
    listingCode: "ARP-2026-009",
    title: "Metroya Yakın 2+1 Daire",
    description: "Yakacık'ta yeni yapı, metro hattına yakın daire.",
    price: 5600000,
    city: "İstanbul",
    district: "Kartal",
    neighborhood: "Yakacık",
    propertyType: "daire",
    rooms: "2+1",
    areaM2: 100,
    status: "pasif",
    agentId: "agent-2",
    updatedAt: "2026-07-02T09:00:00.000Z",
  },
  {
    id: "prop-010",
    listingCode: "ARP-2026-010",
    title: "Orman Manzaralı Villa",
    description: "Zekeriyaköy'de doğayla iç içe, güvenlikli sitede villa.",
    price: 11000000,
    city: "İstanbul",
    district: "Sarıyer",
    neighborhood: "Zekeriyaköy",
    propertyType: "villa",
    rooms: "4+1",
    areaM2: 280,
    status: "aktif",
    agentId: "agent-3",
    updatedAt: "2026-07-20T15:30:00.000Z",
  },
  {
    id: "prop-011",
    listingCode: "ARP-2026-011",
    title: "Tarihi Dokuda 1+1 Daire",
    description: "Balat'ta restore edilmiş binada, tarihi dokuda daire.",
    price: 3900000,
    city: "İstanbul",
    district: "Fatih",
    neighborhood: "Balat",
    propertyType: "daire",
    rooms: "1+1",
    areaM2: 55,
    status: "kiralandi",
    agentId: "agent-4",
    updatedAt: "2026-07-16T11:00:00.000Z",
  },
  {
    id: "prop-012",
    listingCode: "ARP-2026-012",
    title: "Yeni Yapı 3+1 Daire",
    description: "Altunizade'de yeni teslim, otoparklı, asansörlü bina.",
    price: 7500000,
    city: "İstanbul",
    district: "Üsküdar",
    neighborhood: "Altunizade",
    propertyType: "daire",
    rooms: "3+1",
    areaM2: 140,
    status: "aktif",
    agentId: "agent-1",
    updatedAt: "2026-07-19T09:00:00.000Z",
  },
  {
    id: "prop-013",
    listingCode: "ARP-2026-013",
    title: "Merkezi Ofis Katı",
    description: "Levent'te plazada, tam donanımlı, kiralanabilir ofis katı.",
    price: 12500000,
    city: "İstanbul",
    district: "Şişli",
    neighborhood: "Levent",
    propertyType: "ofis",
    rooms: "-",
    areaM2: 220,
    status: "aktif",
    agentId: "agent-2",
    updatedAt: "2026-07-14T10:00:00.000Z",
  },
  {
    id: "prop-014",
    listingCode: "ARP-2026-014",
    title: "Ana Cadde Üzeri Dükkan",
    description: "Bahariye Caddesi üzerinde, yüksek yaya trafiğine sahip dükkan.",
    price: 2200000,
    city: "İstanbul",
    district: "Kadıköy",
    neighborhood: "Bahariye",
    propertyType: "isyeri",
    rooms: "-",
    areaM2: 85,
    status: "kiralandi",
    agentId: "agent-3",
    updatedAt: "2026-07-08T09:00:00.000Z",
  },
  {
    id: "prop-015",
    listingCode: "ARP-2026-015",
    title: "Yatırımlık Arsa",
    description: "İmarlı, yola cepheli, yatırıma uygun köşe arsa.",
    price: 4800000,
    city: "İstanbul",
    district: "Çekmeköy",
    neighborhood: "Merkez",
    propertyType: "arsa",
    rooms: "-",
    areaM2: 500,
    status: "aktif",
    agentId: "agent-4",
    updatedAt: "2026-06-28T09:00:00.000Z",
  },
  {
    id: "prop-016",
    listingCode: "ARP-2026-016",
    title: "Çankaya'da 4+1 Daire",
    description: "Çayyolu'nda geniş bahçeli sitede, aileler için uygun daire.",
    price: 6100000,
    city: "Ankara",
    district: "Çankaya",
    neighborhood: "Çayyolu",
    propertyType: "daire",
    rooms: "4+1",
    areaM2: 190,
    status: "aktif",
    agentId: "agent-1",
    updatedAt: "2026-07-12T09:00:00.000Z",
  },
  {
    id: "prop-017",
    listingCode: "ARP-2026-017",
    title: "Nilüfer'de 3+1 Daire",
    description: "Görükle'de üniversiteye yakın, kiracılı yatırımlık daire.",
    price: 3400000,
    city: "Bursa",
    district: "Nilüfer",
    neighborhood: "Görükle",
    propertyType: "daire",
    rooms: "3+1",
    areaM2: 125,
    status: "pasif",
    agentId: "agent-2",
    updatedAt: "2026-06-25T09:00:00.000Z",
  },
  {
    id: "prop-018",
    listingCode: "ARP-2026-018",
    title: "Sahil Şeridi Villa",
    description: "Ilıca sahiline sıfır, özel iskeleli, lüks villa.",
    price: 18500000,
    city: "İzmir",
    district: "Çeşme",
    neighborhood: "Ilıca",
    propertyType: "villa",
    rooms: "5+1",
    areaM2: 350,
    status: "satildi",
    agentId: "agent-3",
    updatedAt: "2026-07-11T09:00:00.000Z",
  },
];

export function getPropertyById(id: string): Property | undefined {
  return mockProperties.find((property) => property.id === id);
}
